// Регистрация всех кастомных нод для React Flow.
// Этот объект передаётся в <ReactFlow nodeTypes={...} />.
import {
  StartNode,
  EndNode,
  WaitNode,
  MoveNode,
  FollowPathNode,
  SetPositionNode,
  ActorCreateNode,
  ActorDestroyNode,
  AnimateNode,
  SetFacingNode,
  SetDepthNode,
  DialogueNode,
  WaitForDialogueNode,
  CameraTrackNode,
  CameraTrackUntilStopNode,
  CameraPanNode,
  CameraPanObjNode,
  CameraCenterNode,
  ParallelStartNode,
  ParallelJoinNode,
  BranchNode,
  RunFunctionNode,
  CameraShakeNode,
  AutoFacingNode,
  AutoWalkNode,
  TweenNode,
  TweenCameraNode,
  SetPropertyNode,
  FadeInNode,
  FadeOutNode,
  PlaySFXNode,
  EmoteNode,
  JumpNode,
  HaltNode,
  FlipNode,
  SpinNode,
  ShakeObjectNode,
  SetVisibleNode,
  InstantModeNode,
  MarkNodeNode
} from './CutsceneNodes'

// Маппинг: тип ноды → React-компонент.
// React Flow использует этот объект, чтобы рендерить правильный компонент для каждого типа.
export const cutsceneNodeTypes = {
  start: StartNode,
  end: EndNode,
  wait: WaitNode,
  move: MoveNode,
  follow_path: FollowPathNode,
  set_position: SetPositionNode,
  actor_create: ActorCreateNode,
  actor_destroy: ActorDestroyNode,
  animate: AnimateNode,
  set_facing: SetFacingNode,
  set_depth: SetDepthNode,
  dialogue: DialogueNode,
  wait_for_dialogue: WaitForDialogueNode,
  camera_track: CameraTrackNode,
  camera_track_until_stop: CameraTrackUntilStopNode,
  camera_pan: CameraPanNode,
  camera_pan_obj: CameraPanObjNode,
  camera_center: CameraCenterNode,
  // Parallel делаем как пару нод: fork + join.
  parallel_start: ParallelStartNode,
  parallel_join: ParallelJoinNode,
  branch: BranchNode,
  run_function: RunFunctionNode,
  camera_shake: CameraShakeNode,
  auto_facing: AutoFacingNode,
  auto_walk: AutoWalkNode,
  tween: TweenNode,
  tween_camera: TweenCameraNode,
  set_property: SetPropertyNode,
  fade_in: FadeInNode,
  fade_out: FadeOutNode,
  play_sfx: PlaySFXNode,
  emote: EmoteNode,
  jump: JumpNode,
  halt: HaltNode,
  flip: FlipNode,
  spin: SpinNode,
  shake_object: ShakeObjectNode,
  set_visible: SetVisibleNode,
  instant_mode: InstantModeNode,
  mark_node: MarkNodeNode
} as const
